name: 'C++ CI'

on:
  push:
    branches:
      - main
      - feature/github_actions

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential libgtest-dev
      #    sudo apt install libboost-system-dev libboost-filesystem-dev \
      #           libboost-regex-dev libboost-program-options-dev

      #- name: Build and install GTest
      #  run: |
      #    cd /usr/src/gtest
      #    sudo cmake CMakeLists.txt
      #    sudo make
      #    sudo cp lib/*.a /usr/lib
      
      - name: Configure CMake
        run: cmake -B build -DPATCH_VERSION=${{ github.run_number }}

      - name: Build project
        run: cmake --build build
        
      #- name: Run tests
      #  run: |
      #    cd build
      #    ctest --verbose
          
      - name: Run main application
        run: |
          cd build
          ./async

      - name: Create package
        run: cmake --build build --target package

      - name: Create Release
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/feature/github_actions')
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v0.0.${{ github.run_number }}
          release_name: Release v0.0.${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Rename package
        run: |
          cd build
          mv async-0.0.${{ github.run_number }}-Linux.deb async.deb

      - name: Upload Release Asset
        if: steps.create_release.outputs.id != ''
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/async.deb
          asset_name: async.deb
          asset_content_type: application/vnd.debian.binary-package
